def pendule(tentative: int):
    if tentative == 0:
        print()
        print(" +---+")
        print(" |   |")
        print(" |   O")
        print(" |  /|\\")
        print(" |  / \\")
        print("_|_")
        print("| |")
    elif tentative == 1:
        print()
        print(" +---+")
        print(" |   |")
        print(" |   O")
        print(" |  /|\\")
        print(" |  /   ")
        print("_|_")
        print("| |")
    elif tentative == 2:
        print()
        print(" +---+")
        print(" |   |")
        print(" |   O")
        print(" |  /|\\")
        print(" |      ")
        print("_|_")
        print("| |")
    elif tentative == 3:
        print()
        print(" +---+")
        print(" |   |")
        print(" |   O")
        print(" |  /|  ")
        print(" |      ")
        print("_|_")
        print("| |")
    elif tentative == 4:
        print()
        print(" +---+")
        print(" |   |")
        print(" |   O")
        print(" |  /   ")
        print(" |      ")
        print("_|_")
        print("| |")
    elif tentative == 5:
        print()
        print(" +---+")
        print(" |   |")
        print(" |   O")
        print(" |      ")
        print(" |      ")
        print("_|_")
        print("| |")
    elif tentative == 6:
        print()
        print(" +---+")
        print(" |   |")
        print(" |    ")
        print(" |      ")
        print(" |      ")
        print("_|_")
        print("| |")